spring:
    application:
        name: java-time-tracker
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/time_tracker_db
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update

server:
    port: 8080

logging:
    level:
        org.hibernate: error
        org.springframework.web: trace

app:
    task-ttl: 5d
    time-zone: UTC

springdoc:
    swagger-ui:
        path: /swagger-ui